language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
addons:
  apt:
    packages:
      - python-rsa
env:
  - GOOGLE_APPLICATION_CREDENTIALS="$GOPATH/src/github.com/someone1/gcp-jwt-go/credentials.json"
    KMS_TEST_KEYS="$GOPATH/src/github.com/someone1/gcp-jwt-go/kms-test-keys.json"
before_install:
  - openssl aes-256-cbc -K $encrypted_b9c0b4811a94_key -iv $encrypted_b9c0b4811a94_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - go get github.com/mattn/goveralls
  - go get github.com/alecthomas/gometalinter
install:
  - "cd $GOPATH && $GOPATH/bin/gometalinter --install"
  - mkdir /tmp/sdk
  - curl -o /tmp/sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.70.zip"
  - unzip -q /tmp/sdk.zip -d /tmp/sdk
  - export PATH="$PATH:/tmp/sdk/go_appengine"
  - export APPENGINE_DEV_APPSERVER=/tmp/sdk/go_appengine/dev_appserver.py
  - cd $GOPATH/src/github.com/someone1/gcp-jwt-go
  - export GO111MODULE="on"

script:
  - make test-coverage
  - make test-appengine-coverage
  - cat ae_coverage.out | grep .go >> coverage.out
  - "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
  - make fmt vet build
